version: '3'

services:
  modelsback:
    build: .
    ports: 
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app # named volume Sourcehote:dossierDocker
      - /usr/src/app/node_modules # anonymous volume for node_modules only
  mysql:
    image: mysql:latest
    volumes: 
      - "../test/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ******
    ports:
      - "3307:3306"




