version: '3'

services:
  modelsback:
    build: .
    ports: 
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app # named volume
      - /usr/src/app/node_modules # anonymous volume for node_modules only